# SPDX-FileCopyrightText: 2016-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# You can add one username per supported platform and one custom link
custom: https://nextcloud.com/include/
