name: releaseTest

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    releaseTest:
        environment: test
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Run release test
                run: | 
                  echo ${{ secrets.TEST }}
                  echo ${{ secrets.LEAKED_SECRET }}
