codecov:
  bot: nextcloud-android-bot
    token: fc506ba4-33c3-43e4-a760-aada38c24fd5
  branch: master
  ci:
    - drone.nextcloud.com

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, uncovered, tree"
  require_changes: false
  require_base: no
  require_head: no
  behavior: spammy

ignore:
  - "src/main/res/values*/*"

