codecov:
  bot: nextcloud-android-bot
    token: df7b84c0-3ab4-48a7-8ba2-1ad8ddbc96e1
  branch: master
  ci:
    - drone.nextcloud.com

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, uncovered, tree"
  require_changes: false
  require_base: no
  require_head: no
  behavior: spammy

ignore:
  - "src/main/res/values*/*"

