pipeline:
  test:
    image: nextcloudci/android:android-26
    commands:
      # uncomment gplay for Gplay, Modified only
      - sh -c "if [ '$FLAVOUR' != 'Generic' ]; then sed -i '/.*com.google.*/s/^.*\\/\\///g' build.gradle; fi"

      # - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
      # - emulator -avd test -no-window &
      # - ./wait_for_emulator.sh

      # build app and assemble APK, in debug mode
      - sh -c "if [ '$FLAVOUR' != 'Lint' ]; then ./gradlew assemble${FLAVOUR}; fi"

      # run all the instrumented tests of app module - DISABLED until we get an stable setup for Espresso in Travis
      # - ./gradlew connectedDebugAndroidTest --info

      # install app, then assemble and install instrumented tests of app module
      # - ./gradlew :install${FLAVOUR}Debug
      # - ./gradlew :install${FLAVOUR}DebugAndroidTest

      # run sample instrumented unit test
      # TODO fails because test runner is not available
      #- adb shell am instrument -w -e debug false -e class com.owncloud.android.datamodel.OCFileUnitTest com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner

    environment:
      - ANDROID_TARGET=android-24
      - ANDROID_ABI=armeabi-v7a
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/opt/android-sdk-linux/tools/lib64/gles_mesa/

  lint:
    image: nextcloudci/android:android-26
    commands:
      # needs gplay
      - sed -i '/.*com.google.*/s/^.*\\/\\///g' build.gradle
      - export BRANCH=$(scripts/lint/getBranchName.sh $GIT_USERNAME $GIT_TOKEN $DRONE_PULL_REQUEST)
      - scripts/lint/lint-up-wrapper.sh $GIT_USERNAME $GIT_TOKEN $BRANCH $LOG_USERNAME $LOG_PASSWORD $DRONE_BUILD_NUMBER
    secrets: [ GIT_USERNAME, GIT_TOKEN, LOG_USERNAME, LOG_PASSWORD ]
    when:
      matrix:
        FLAVOUR: Lint

matrix:
  FLAVOUR:
    - Generic
    - Gplay
    - Modified
    - Lint

branches: master
