pipeline:
#  test:
#    image: nextcloudci/android:android-18
#    commands:
#      - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
#      - emulator -avd test -no-window &
#      - ./wait_for_emulator.sh
#      # build app and assemble APK, in debug mode
#      - ./gradlew assembleGeneric
#      # run all the instrumented tests of app module - DISABLED until we get an stable setup for Espresso in Travis
#      # - ./gradlew connectedDebugAndroidTest --info
#      # install app, then assemble and install instrumented tests of app module
#      - ./gradlew :installGenericDebug
#      #- ./gradlew :installModifiedDebug
#      - ./gradlew :installGenericDebugAndroidTest
#      #- ./gradlew :installModifiedDebugAndroidTest
#      # run sample instrumented unit test
#      # TODO fails because test runner is not available
#      #- adb shell am instrument -w -e debug false -e class com.owncloud.android.datamodel.OCFileUnitTest com.owncloud.android.test/android.support.test.runner.AndroidJUnitRunner
#
#    environment:
#      - ANDROID_TARGET=android-24
#      - ANDROID_ABI=armeabi-v7a
#      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/opt/android-sdk-linux/tools/lib64/gles_mesa/

  lint:
    image: nextcloudci/android:android-18
    commands:
      # needs gplay
      - sh -c "sed -i '/com.google.*.gms/s/^.*\/\///g' build.gradle"
      - BRANCH=$(curl 2>/dev/null -u ${GIT_USERNAME}:${GIT_TOKEN} https://api.github.com/repos/nextcloud/android/pulls/565  |  grep \"ref\": /tmp/t1 | grep -v master | cut -d"\"" -f4)
      - ruby scripts/lint/lint-up.rb ${GIT_USERNAME} ${GIT_TOKEN} $BRANCH

branches: master