version: 2

# General settings to apply
always_pending:
  title_regex: '(WIP|wip)'
  labels:
    - 1. developing
  # custom message that will be used for the GitHub status
  explanation: 'This PR is a work in progress...'

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  author_approval:
    ignored: true
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:|:\+1:|LGTM|Merge)'
    reject_regex: '^(Rejected|:-1:)'
  reset_on_push:
    enabled: false
  reset_on_reopened:
    enabled: true
  conditions:
    labels:
      exclude:
        - dependencies

groups:
  code-review:
    required: 1
    reject_value: -99
    users:
      - AndyScherzinger
      - tobiasKaminsky
      - mario
      - przybylski
      - ardevd

  design-review:
    conditions:
      labels:
      - design
    reset_on_push:
      enabled: false
    required: 1
    reject_value: -99
    users:
      - jancborchardt
      - eppfel
