# suppress inspection "UnusedProperty"
net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache
net.fortuna.ical4j.timezone.registry=com.nextcloud.utils.ical.AndroidCompatTimeZoneRegistryFactory
