# SPDX-FileCopyrightText: 2017-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later OR GPL-2.0-only


## config
# add following to your shell rc:
# export FASTLANE_NEXTCLOUD_UPLOAD_STORE_FILE=""
# export FASTLANE_NEXTCLOUD_UPLOAD_STORE_PASSWORD=""
# export FASTLANE_NEXTCLOUD_UPLOAD_KEY_ALIAS=""
# export FASTLANE_NEXTCLOUD_UPLOAD_KEY_PASSWORD=""
# export FASTLANE_NEXTCLOUD_GITHUB_API_TOKEN=""
# export FASTLANE_NEXTCLOUD_HUAWEI_CLIENT_ID=""
# export FASTLANE_NEXTCLOUD_HUAWEI_CLIENT_SECRET=""
# export FASTLANE_NEXTCLOUD_HUAWEI_APP_ID=""

skip_docs


APP="files"
REPO="nextcloud/android"

GRADLE_SIGNING_PROPERTIES = {
  "android.injected.signing.store.file" => ENV["FASTLANE_NEXTCLOUD_UPLOAD_STORE_FILE"],
  "android.injected.signing.store.password" => ENV["FASTLANE_NEXTCLOUD_UPLOAD_STORE_PASSWORD"],
  "android.injected.signing.key.alias" => ENV["FASTLANE_NEXTCLOUD_UPLOAD_KEY_ALIAS"],
  "android.injected.signing.key.password" => ENV["FASTLANE_NEXTCLOUD_UPLOAD_KEY_PASSWORD"],
}.freeze

import("./common.Fastfile")

platform :android do
    
    desc "Release phase 2 for RC: checks, tag, upload gplay to playstore with values from build.gradle.kts"
    lane :RC_releasePhase2 do |options|
        checkReleaseRequirements_RC()
        info = androidVersion
        promptVersion(info)
        checkChangelog(info)
        checkLibrary_RC()
        checkIfScreenshotsExist()
        checkIfAPKexists()
        tag(info)
        uploadToPlaystore_RC(info)
        createGithubRelease_RC(info)
        fdroidMergeRequest_RC(info)
        createChangelogPullRequest_RC(info)
    end
    
    desc "Release phase 2 for FINAL: checks, tag, upload gplay to playstore with values from build.gradle.kts"
    lane :Final_releasePhase2 do |options|
        checkReleaseRequirements_Final()
        info = androidVersion
        promptVersion(info)
        checkChangelog(info)
        checkLibrary_Final()
        checkIfScreenshotsExist()
        checkIfAPKexists()
        tag(info)
        uploadToPlaystore_Final(info)
        createGithubRelease_Final(info)
        fdroidMergeRequest_Final(info)
        createChangelogPullRequest_Final(info)
        uploadToHuawei_Final(info)
    end

    # to install
    # bundle exec fastlane add_plugin huawei_appgallery_connect
    # bundle install --path build/vendor/bundle
    private_lane :uploadToHuawei_Final do |options|
        huawei_appgallery_connect(
            client_id: ENV["FASTLANE_NEXTCLOUD_HUAWEI_CLIENT_ID"],
            client_secret: ENV["FASTLANE_NEXTCLOUD_HUAWEI_CLIENT_SECRET"],
            app_id: ENV["FASTLANE_NEXTCLOUD_HUAWEI_APP_ID"],
            apk_path: "release/huawei-release-" + options["versionCode"] + ".apk",
            submit_for_review: true,
            delay_before_submit_for_review: 30,
        )
    end
    
    ## private lanes  
    private_lane :checkReleaseRequirements_common do
        sh("if ! command -v fdroid &>/dev/null; then echo 'fdroid command not found' && exit 1; fi")
        sh("if ! command -v bundletool &>/dev/null; then echo 'bundletool command not found' && exit 1; fi")
    end
    
    private_lane :checkReleaseRequirements_RC do
        checkReleaseRequirements_common()
        sh("if ! command -v fdroidMergeRequestRC &>/dev/null; then echo 'fdroidMergeRequestRC command not found'; exit 1; fi")
        sh("if ! command -v createChangelogPullRequestRC &>/dev/null; then echo 'createChangelogPullRequestRC command not found'; exit 1; fi")
    end
    
    private_lane :checkReleaseRequirements_Final do
        checkReleaseRequirements_common()
        sh("if ! command -v fdroidMergeRequestFinal &>/dev/null; then echo 'fdroidMergeRequestFinal command not found'; exit 1; fi")
        sh("if ! command -v createChangelogPullRequestFinal &>/dev/null; then echo 'createChangelogPullRequestFinal command not found'; exit 1; fi")
    end
    
    private_lane :createChangelogPullRequest_RC do |options|
        sh("createChangelogPullRequestRC " +  options["tag"] + " \"" + options["versionName"] + "\" " + options["versionCode"] + " \"" + options["branch"] + "\" ")
    end
    
    private_lane :createChangelogPullRequest_Final do |options|
        sh("createChangelogPullRequestFinal " +  options["tag"] + " \"" + options["versionName"] + "\" " + options["versionCode"] + " \"" + options["branch"] + "\" ")
    end
    
    private_lane :checkIfAPKexists do |options|
        sh("if [ $(/bin/ls -1 ../release | wc -l) -ne 4 ]; then echo 'Release artifacts not present or wrong number present; aborting!' ; exit 1 ;
         fi")
    end
    
    desc "Show versions and prompt for confirmation"
    private_lane :promptVersion do |options|
        print "VersionCode: " + options["versionCode"].to_s + "\n"
        print "Name: " + options["versionName"] + "\n"
        print "Tag: " + options["tag"] + "\n"
        print "Branch: " + options["branch"] + "\n"
    
        answer = prompt(text: "is this okay?", boolean: true)
    
        if !answer
            exit
        end
    end
    
    desc "check if library is set correctly"
    private_lane :checkLibrary_RC do
        sh(" if [ $(egrep 'androidLibraryVersion.*master.*' ../build.gradle.kts -c) -eq 1 ] ; then echo 'Library is set to master tag; aborting!' ; exit 1 ; fi")
    end
    
    desc "check if library is set correctly: must NOT contain master nor rc"
    private_lane :checkLibrary_Final do
        sh(" if [ $(grep 'androidLibraryVersion' ../build.gradle.kts | egrep 'master|rc' -c) -eq 1 ] ; then echo 'Library is still set to rc tag; aborting!' ; exit 1 ; fi")
    end
    
    desc "check if screenshots exists and exit"
    private_lane :checkIfScreenshotsExist do
        sh(" if [ $(find metadata/android/*/images -type f -not -name icon.png  | grep -c . ) -gt 0 ] ; then echo 'Screenshots in fastlane folder exist; aborting!' ; exit 1 ; fi")
    end
        
    private_lane :createGithubRelease_RC do |options|
        set_github_release(
            repository_name: REPO,
            api_token: ENV["FASTLANE_NEXTCLOUD_GITHUB_API_TOKEN"],
            name: options["versionName"],
            tag_name: options["tag"],
            is_prerelease: true,
            description: (File.read("metadata/android/en-US/changelogs/" + options["versionCode"] + ".txt") rescue "No changelog provided"),
            upload_assets: [ "release/gplay-release-" + options["versionCode"] + ".apk", "release/nextcloud-" +
            options["versionCode"] + ".apk" ]
        )
    end
    
    private_lane :createGithubRelease_Final do |options|
        set_github_release(
            repository_name: REPO,
            api_token: ENV["FASTLANE_NEXTCLOUD_GITHUB_API_TOKEN"],
            name: options["versionName"],
            tag_name: options["tag"],
            description: (File.read("metadata/android/en-US/changelogs/" + options["versionCode"] + ".txt") rescue "No changelog provided"),
            upload_assets: Dir.glob("release/*.apk")
        )
    end
    
    private_lane :fdroidMergeRequest_RC do |options|
       sh("fdroidMergeRequestRC " +  options["tag"] + " \"" + options["versionName"] + "\" " + options["versionCode"])
    end
    
    private_lane :fdroidMergeRequest_Final do |options|
       sh("fdroidMergeRequestFinal " +  options["tag"] + " \"" + options["versionName"] + "\" " + options["versionCode"])
    end
    
    private_lane :checkChangelog do |options|
        sh(" if [ ! -e  metadata/android/en-US/changelogs/" + options["versionCode"] + ".txt ] ; then echo 'Changelog fastlane/metadata/android/en-US/changelogs/" + options["versionCode"] + ".txt does not exist' ; exit 1 ; fi")
        sh(" if [ $(wc -m metadata/android/en-US/changelogs/" + options["versionCode"] + ".txt | cut -d' ' -f1) -ge 500 ] ; then echo 'Changlog more than 500 chars' ; exit 1 ; fi")
    end




    ## to discuss if still needed
    lane :screenshotsPhone do
        beautifyPhone()
        build_for_screengrab()
    
        screengrab(
            device_type: "phone",
            app_apk_path: APK_LOCATION,
            tests_apk_path: TEST_APK_LOCATION
        )
    end
    
    lane :screenshotsTablet do
        beautifyPhone()
        build_for_screengrab()
    
        screengrab(
            device_type: "sevenInch",
            app_apk_path: APK_LOCATION,
            tests_apk_path: TEST_APK_LOCATION
        )
    end

  desc "Beautify phone for screenshots: set time, remove other icons, no charging"
    lane :beautifyPhone do
        sh("adb shell settings put global sysui_demo_allowed 1")
        sh("adb shell am broadcast -a com.android.systemui.demo -e command clock -e hhmm 1200")
        sh("adb shell am broadcast -a com.android.systemui.demo -e command network -e mobile show -e level 4 -e datatype false")
        sh("adb shell am broadcast -a com.android.systemui.demo -e command notifications -e visible false")
        sh("adb shell am broadcast -a com.android.systemui.demo -e command battery -e plugged false -e level 100")
    end

  desc "Build debug and test APK for screenshots"
    private_lane :build_for_screengrab do
        build_android_app(
          task: 'assemble',
          flavor: 'Generic',
          build_type: 'Debug'
        )
        APK_LOCATION = lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].select{ |i| i[/00/] }[0]
    
        build_android_app(
          task: 'assemble',
          flavor: 'Generic',
          build_type: 'DebugAndroidTest'
        )
        TEST_APK_LOCATION = lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].select{ |i| i[/androidTest/] }[0]
    end

end
