#!/bin/bash

statusFile="betaUpdateStatus"

git pull -q || exit

branches=$(scripts/getBranchesForBeta)
branchesCount=$(echo "$branches" | wc -l)
count=1

date +%F > $statusFile
echo "Branches: $branchesCount" >> $statusFile

while read -r branch; do
    echo -n "[$(printf "%02d" $count) / $(printf "%02d" $branchesCount)] " >> $statusFile
    
    branchName=$(echo $branch | cut -d"(" -f2 | cut -d")" -f1 | tr ":" "/")
    
    if [ $(echo $branchName | grep -c "^origin") -eq 0 ] ; then
        # remote repo
        git fetch -q $(echo $branchName | cut -f1 -d"/") 1> /dev/null
    fi
    
    git merge --no-edit $branchName 1> /dev/null
    
    if [ $? -ne 0 ] ; then
        echo "$branch CONFLICT" >> $statusFile
        git merge --abort
    else
        echo "$branch merged successfully" >> $statusFile
    fi
    
    let count++
done <<< "$branches"

## Update Changelog.md
tmpFile=$(tempfile)
cp CHANGELOG.md $tmpFile

echo "## $(date +%F)" > CHANGELOG.md

## add new branches
if [ $(comm -13 branches_old <(cat betaUpdateStatus | grep succ | cut -d"(" -f2 | cut -d")" -f1 | sort) | wc -l) -gt 0 ] ; then
    egrep "$(comm -13 branches_old <(cat betaUpdateStatus | grep succ | cut -d"(" -f2 | cut -d")" -f1 | sort) )" betaUpdateStatus | cut -d"]" -f2 | sed s'#$#]#'g | sed s'#^#-#'g | sed s'#$# added#'g >> CHANGELOG.md
fi
cat betaUpdateStatus | grep succ | cut -d"(" -f2 | cut -d")" -f1 | sort > branches_old

echo >> CHANGELOG.md

## add updated branches
if [ $(cat betaUpdateStatus | grep succ -c) -gt 0 ]; then
    cat betaUpdateStatus | grep succ | cut -d"]" -f2 | sed s'#$#]#'g | sed s'#^#-#'g | sed s'#$# updated#'g >> CHANGELOG.md
fi

echo >> CHANGELOG.md
cat $tmpFile >> CHANGELOG.md

git add .
git commit -m "daily beta build"
git push
