name: "Detect snapshot"

on:
    push:
        branches: [ master, stable-* ]
    pull_request:
        branches: [ master, stable-* ]

jobs:
    detectSnapshot:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectSNAPSHOT.sh
